export const LocationActionTypes = {
  SET_LOCATION_LIST: "SET_LOCATION_LIST",
  SET__HOME_SELECTED_LOCATION: "SET__HOME_SELECTED_LOCATION",
  SET_CURRENT_LOCATION: "SET_CURRENT_LOCATION",
  SET_LOCATION_VALUES: "SET_LOCATION_VALUES",
};
