export const AppActionTypes = {
	SET_CONSUME_VALUES : 'SET_CONSUME_VALUES',
	SET_EXPOSE_VALUES  : 'SET_EXPOSE_VALUES',
	SET_SKIP_MODE:'SET_SKIP_MODE',
	SET_APP_CONFIGS: 'SET_APP_CONFIGS',
	SET_APP_LOADING:'SET_APP_LOADING',
	SET_APP_ERROR:'SET_APP_ERROR',
	SET_APP_WEBVIEW:'SET_APP_WEBVIEW',
	SET_APP_SUCCESS: 'SET_APP_SUCCESS',
	SET_IS_DEMOGRAPHIC_VISIBLE:'SET_IS_DEMOGRAPHIC_VISIBLE',
	SET_DISMISS_DEMOGRAPHIC:'SET_DISMISS_DEMOGRAPHIC',

};
