export const OutletActionTypes = {
  SET_OUTLET_LIST: "SET_OUTLET_LIST",
  SET_HOME_SELECTED_OUTLET: "SET_HOME_SELECTED_OUTLET",
  SET_CURRENT_OUTLET: "SET_CURRENT_OUTLET",
  SET_OUTLET_VALUES: "SET_OUTLET_VALUES",
  SET_MERCHANT_DATA: "SET_MERCHANT_DATA",
  SET_SELECTED_FILTER: "SET_SELECTED_FILTER",
  SET_SELECTED_FILTER_RESET: "SET_SELECTED_FILTER_RESET",
  SET_FAVOURITE_LIST: "SET_FAVOURITE_LIST",
};
