export const UserActionTypes = {
	SET_CONSUME_VALUES : 'SET_CONSUME_VALUES',
	SET_EXPOSE_VALUES  : 'SET_EXPOSE_VALUES',
	SET_USER  : 'SET_USER',
	SET_TOKEN : 'SET_TOKEN',
	SET_USER_VALUES : 'SET_USER_VALUES'
};
