export const defaultLocations = [
  {
    active: true,
    lat: 25.300579,
    name: "Dubai & N. Emirates",
    is_careem_enabled: 0,
    flag: "AE",
    currency: "AED",
    lng: 55.307709,
    reload_background: false,
    id: 1,
    is_show_category: false,
    background:
      "https://s3-us-west-2.amazonaws.com/product-locations/backgrounds/1.png",
    language: "ar",
    flagImage: require("../images/flags/AE.png"),
  },
  {
    active: true,
    lat: 30.051861,
    name: "Egypt",
    is_careem_enabled: 0,
    flag: "EG",
    currency: "EGP",
    lng: 31.235107,
    reload_background: false,
    id: 6,
    is_show_category: false,
    background:
      "https://s3-us-west-2.amazonaws.com/product-locations/backgrounds/6.png",
    language: "ar",
    flagImage: require("../images/flags/EG.png"),
  },
  {
    active: true,
    lat: 25.296234,
    name: "Qatar",
    is_careem_enabled: 0,
    flag: "QA",
    currency: "QAR",
    lng: 51.521652,
    reload_background: false,
    id: 9,
    is_show_category: false,
    background:
      "https://s3-us-west-2.amazonaws.com/product-locations/backgrounds/9.png",
    language: "ar",
    flagImage: require("../images/flags/QA.png"),
  },
  {
    active: true,
    lat: 26.22876,
    name: "Bahrain",
    is_careem_enabled: 0,
    flag: "BH",
    currency: "BHD",
    lng: 50.584381,
    reload_background: false,
    id: 3,
    is_show_category: false,
    background:
      "https://s3-us-west-2.amazonaws.com/product-locations/backgrounds/3.png",
    language: "ar",
    flagImage: require("../images/flags/BH.png"),
  },
  {
    active: true,
    lat: 29.372301,
    name: "Kuwait",
    is_careem_enabled: 0,
    flag: "KW",
    currency: "KWD",
    lng: 47.97847,
    reload_background: false,
    id: 7,
    is_show_category: false,
    background:
      "https://s3-us-west-2.amazonaws.com/product-locations/backgrounds/7.png",
    language: "ar",
    flagImage: require("../images/flags/KW.png"),
  },
  {
    active: true,
    lat: 22.295401,
    name: "Eastern province",
    is_careem_enabled: 0,
    flag: "SA",
    currency: "SAR",
    lng: 50.679401,
    reload_background: true,
    id: 49,
    is_show_category: false,
    background:
      "https://s3-us-west-2.amazonaws.com/product-locations/backgrounds/1.png",
    language: "ar",
    flagImage: require("../images/flags/SA.png"),
  },
  {
    active: true,
    lat: 24.771772,
    name: "Riyadh & E. Prov",
    is_careem_enabled: 0,
    flag: "SA",
    currency: "SAR",
    lng: 46.727173,
    reload_background: false,
    id: 10,
    is_show_category: false,
    background:
      "https://s3-us-west-2.amazonaws.com/product-locations/backgrounds/10.png",
    language: "ar",
    flagImage: require("../images/flags/SA.png"),
  },
  {
    active: true,
    lat: 21.606365,
    name: "Jeddah",
    is_careem_enabled: 0,
    flag: "SA",
    currency: "SAR",
    lng: 39.171326,
    reload_background: false,
    id: 18,
    is_show_category: false,
    background:
      "https://s3-us-west-2.amazonaws.com/product-locations/backgrounds/18.png",
    language: "ar",
    flagImage: require("../images/flags/SA.png"),
  },
  {
    active: true,
    lat: 24.534632,
    name: "Abu Dhabi & Al Ain",
    is_careem_enabled: 0,
    flag: "AE",
    currency: "AED",
    lng: 54.362671,
    reload_background: false,
    id: 2,
    is_show_category: false,
    background:
      "https://s3-us-west-2.amazonaws.com/product-locations/backgrounds/2.png",
    language: "ar",
    flagImage: require("../images/flags/AE.png"),
  },
  {
    active: true,
    lat: 31.958279,
    name: "Jordan",
    is_careem_enabled: 0,
    flag: "JO",
    currency: "JOD",
    lng: 35.945621,
    reload_background: false,
    id: 16,
    is_show_category: false,
    background:
      "https://s3-us-west-2.amazonaws.com/product-locations/backgrounds/16.png",
    language: "ar",
    flagImage: require("../images/flags/JO.png"),
  },
];

export const CategoryData = {
  FoodAndDrink: {
    displayName: "FOOD & Drink",
    apiName: "Restaurants and Bars",
  },

  BeautyAndFitness: {
    displayName: "BEAUTY & FITNESS",
    apiName: "Body",
  },

  AttractionsAndLeisure: {
    displayName: "ATTRACTIONS & LEISURE",
    apiName: "Leisure",
  },
};
