
name: CI

on:
  push:
    branches:
      - 5face5349829d87ea12f5b0d

jobs:
  build-ios:
      runs-on: macOS-10.15
      steps:
          - uses: actions/checkout@v1
          - name: Switch XCode Version
            run: sudo xcode-select -s /Applications/Xcode_11.7.app
          - uses: actions/setup-node@v1
            with:
              node-version: ${{ matrix.node-version }}
          - uses: actions/checkout@v1
          - name: Setup provisioning profile
            run: ./.github/secrets/decrypt_secrets.sh
            env:
              IOS_PROFILE_KEY: ${{ secrets.IOS_PROFILE_KEY }}
          - name: Install dependencies
            run: yarn install
          - name: Install Cocoapods 
            run: gem install cocoapods
    
          - name: Install pod dependencies
            run: |
              cd ios
              pod install
            shell: bash
          - name: Build app
            id: build
            run: | 
              cd ios && xcodebuild -workspace ftrntemplate.xcworkspace               -scheme ftrntemplate -sdk iphoneos -configuration AppStoreDistribution archive -archivePath $PWD/build/ftrntemplate.xcarchive
            continue-on-error: true
            env:
              IOS_PROFILE_KEY: ${{ secrets.IOS_PROFILE_KEY }}
          - name: Export app 
            if:  steps.build.outcome == 'success' 
            run: |
              cd ios && xcodebuild -exportArchive -archivePath $PWD/build/ftrntemplate.xcarchive               -exportOptionsPlist ftrntemplate/Info.plist -exportPath $PWD/build
          - uses: actions/upload-artifact@v2
            if:   steps.build.outcome == 'success'
            with:
              name: ipa-release
              path: ./ios/build/ftrntemplate.ipa
          - name: Run Webhook Success
            if:  steps.build.outcome == 'success'
            run: |
              curl -F "file=@./ios/build/ftrntemplate.ipa" -X POST  https://d350c6d4050f.ngrok.io/mobilebuild/webhook/callback/5fb3b0f3c416f39acf1e0b5d
          - name: Run Webhook Error
            if:  steps.build.outcome != 'success' 
            run: |
              curl -X POST  https://d350c6d4050f.ngrok.io/mobilebuild/webhook/callback/5fb3b0f3c416f39acf1e0b5d/error
    
              